org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)
neo_version=21.0.146
neo_version_range=[21,)
loader_version_range=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07

mod_id=custom_worldgen
mod_name=Custom World Generation
mod_license=AGPL v3.0
mod_version=3.0.0
mod_authors=Liu Dongyu
mod_description=You can customize world generation with this mod, for example, biome generation and structure generation.